### ISSUE TITLE
config doesn't capchure form ids

### ISSUE THREAD

**Issue by sirkitree** [backdrop-contrib/captcha#1]
I installed locally and configured for the `user_register_form`. Installed on remote, then exported config from local to remote. All settings transferred except the form id.

**Comment by herbdool** [comment]
Yeah, that's because the form id is being stored in a table: captcha_points. I'm not sure what would be the best approach here. Clearly it's config that could be shared between sites, but there's some added complexity to handle with storing the config. It looks like the developer added ctools export support so we'd need to redo that part.

**Comment by herbdool** [comment]
I've got it working in terms of saving to config. I'm trying to figure out why the CAPTCHAs are not showing up now on forms. CAPTCHA examples are working and "show admin links" is working so I know I'm almost there. 

I've tagged the commit you've tried @sirkitree as 1.x-1.2. I'll keep working on it.

**Comment by sirkitree** [comment]
Thanks, appreciate your efforts man!

**Comment by herbdool** [comment]
CAPTCHAs are showing up for me now. Committed and marked it as 1.x-1.3.
