### ISSUE TITLE
Fatal error when trying to configure CAPTCHA 1.x-1.7.2

### ISSUE THREAD

**Issue by JDSaward** [backdrop-contrib/captcha#13]
On Backdrop 1.24.1, Installed CAPTCHA 1.x-1.7.2. Installs OK, but going to configure for first time, at admin/config/people/captcha gives fatal error on screen:

Argument 1 passed to backdrop_sort() must be of the type array, null given, called in /app/modules/contrib/captcha/captcha.inc on line 132 

Reported in site log as:

TypeError: Argument 1 passed to backdrop_sort() must be of the type array, null given, called in /app/modules/contrib/captcha/captcha.inc on line 132 in backdrop_sort() (line 7278 of /app/core/includes/common.inc).

Same error on local site and staging:
- Local site is PHP 7.4.33
- Staging site is: PHP 8.1.17

**Comment by indigoxela** [comment]
Hi @JDSaward, many thanks for reporting.

I can reproduce the problem by deleting all items from "Form protection". In that case "captcha_points" is null, not an array as the code expects. This can get fixed by defensive coding in function captcha_get_captcha_points().

As a quick fix, you could patch the config file captcha.settings.json in your active config directory, `"captcha_points": [],`.
That makes it an array instead of null, and you should be able to edit configuration again.

As an alternative, you could replace the broken captcha.settings.json with the [original file](https://raw.githubusercontent.com/backdrop-contrib/captcha/1.x-1.x/config/captcha.settings.json). Go to /admin/config/development/configuration/single/import and past the functioning json code there. That should fix the problem immediately.

**Comment by indigoxela** [comment]
A pull request is now available for testing: https://github.com/backdrop-contrib/captcha/pull/14

**Comment by JDSaward** [comment]
Replacing the broken captcha.settings.json with the original file solved it for me. Thank you.
